---
# For configuration options and examples, please see:
# https://gethomepage.dev/configs/services/
- S'INSTALLER:
    - Hello:
        href: https://hello.pantagruweb.club/i/ALLOLESPOMPIERS
        description: L'invitation au voyage
        server: local
        container: wizarr

- SE NOURRIR:
    - Baloche:
        href: https://coolections.pantagruweb.club
        description: Sax drogués au Rock and Roll
        container: plex
        server: local   
    - Cinoche:
        href: https://coolections.pantagruweb.club
        description: La manie du cinéma
        server: local
        container: plex
    - Téloche:
        href: https://teloche.pantagruweb.club
        description: Un bourre-pif dans le PAF
        server: local

- LE NOURRIR:
    - Cocagne:
        href: https://cocagne.pantagruweb.club
        description: P2P P2P P2P P2P
        server: local
        container: slskd
    - Jean-Cloude:
        href: https://vip.jeancloude.club/f/48866
        description: Unser Bierbauch
        # widget:
        #     type: nextcloud
        #     url: https://vip.jeancloude.club
        #     user: tristan
        #     password: XRGGE-jmNs3-Fq6f4-eBp3r-xwbc2
        #     fields: ["freespace", "activeusers", "numfiles"]
    - Panurge:
        href: https://panurge.pantagruweb.club
        description: Il vole aux riches pour donner au Cloude !
        server: local
        container: metube