---
# For configuration options and examples, please see:
# https://gethomepage.dev/configs/services/

- My First Group:
    - Plex:
        icon: plex.png
        href: http://localhost
        description: Watch movies and TV shows.
        # server: localhost
        # container: plex

- My Second Group:
    - My Second Service:
        href: http://localhost
        description: Homepage is the best

- My Third Group:
    - My Third Service:
        href: http://localhost/
        description: Homepage is 😎
