---
# For configuration options and examples, please see:
# https://gethomepage.dev/configs/services/

- SE NOURRIR:
    - Salut !:
        href: https://hello.pantagruweb.club/i/ALLOLESPOMPIERS
        description: S'inscrire
        server: local
        container: wizarr
    - Baloche:
        href: https://www.plex.tv/fr/plexamp/
        description: Sax drogués au Rock and Roll
    - Cinoche:
        href: https://coolections.pantagruweb.club
        description: La manie du cinéma
        server: local
        container: plex
    - Téloche:
        href: https://teloche.pantagruweb.club
        description: Un bourre-pif dans le PAF
        server: local
        container: plex

- LE NOURRIR:
    - Cocagne:
        href: https://lidarr.pantagruweb.club
        description: P2P P2P P2P P2P
        server: local
        container: lidarr
        widget:
            type: lidarr
            url: https://lidarr.pantagruweb.club
            fields: ["wanted", "queued", "artists"]
            key: f20545dba32348a49fdd66ddafcfc85d
    - Jean-Cloude:
        href: https://vip.jeancloude.club
        description: Unser Bierbauch
        # widget:
        #     type: nextcloud
        #     url: https://vip.jeancloude.club
        #     key: tristan:XRGGE-jmNs3-Fq6f4-eBp3r-xwbc2
    - Panurge:
        href: https://panurge.pantagruweb.club
        description: Il vole aux riches pour donner au Cloude !
