---
# For configuration options and examples, please see:
# https://gethomepage.dev/configs/services/

- SE NOURRIR:
    - Baloche:
        icon: plex.png
        href: http://localhost
        description: Watch movies and TV shows.
        # server: localhost
        # container: plex
    - Cinoche:
        icon: plex.png
        href: http://localhost
        description: Watch movies and TV shows.
        # server: localhost
        # container: plex
    - Téloche:
        icon: plex.png
        href: http://localhost
        description: Watch movies and TV shows.
        # server: localhost
        # container: plex

- LE NOURRIR:
    - Cocagne:
        href: http://localhost
        description: Homepage is the best
    - Jean-Cloude:
        href: http://localhost
        description: Homepage is the best
    - Panurge:
        href: http://localhost
        description: Homepage is the best