---
# For configuration options and examples, please see:
# https://gethomepage.dev/configs/services/

- SE NOURRIR:
    - Baloche:
        href: http://localhost
        description: Sax drogués au Rock and Roll
        # server: localhost
        # container: plex
    - Cinoche:
        href: http://localhost
        description: La manie du cinéma
        # server: localhost
        # container: plex
    - Téloche:
        href: http://localhost
        description: Un bourre-pif dans le PAF
        # server: localhost
        # container: plex

- LE NOURRIR:
    - Cocagne:
        href: http://localhost
        description: P2P P2P P2P P2P
    - Jean-Cloude:
        href: http://localhost
        description: Le Cloude du Spectacle
    - Panurge:
        href: http://localhost
        description: Il vole aux Riches pour donner au Cloude !