language: fr
title: Pantagruweb
description: A description of my awesome homepage
theme: light # or light
color: pink
headerStyle: clean
useEqualHeights: true
cardBlur: xs # sm, "", md, etc... see https://tailwindcss.com/docs/backdrop-blur