---
# For configuration options and examples, please see:
# https://gethomepage.dev/configs/info-widgets/

- logo:
  href: ../images/panta-logo.png
  target: _blank # Optional, can be set in settings
- search:
    provider: duckduckgo
    target: _blank
