---
# For configuration options and examples, please see:
# https://gethomepage.dev/configs/info-widgets/

- logo:
    icon: http://localhost:3000/icons/panta-logo.png
    href: ../icons/panta-logo.png
    target: _blank # Optional, can be set in settings
# - search:
#     provider: duckduckgo
#     target: _blank
